version: '3'
services:
  desktop: # choose 2560x1440 for display
    image: hossein20s/docker-desktop:ml
    container_name: desktop
    privileged: true
    ports:
      - 6080:80
      - 5900:5900
      - 6901:6901
      - 5000:5000
      - 4000:4000
      - 8000:8000
      - 63342:63342 # pycharm built-in server
    environment:
      USER: guest
      PASSWORD: guest
    cap_add:
      - SYS_PTRACE
    volumes:
      - ~:/opt/host
      - /tmp:/tmp
      - /dev/shm:/dev/shm
  methyl:
    image: joshualevy44/pymethylprocess
    container_name: methyl
    privileged: true
    command: tail -f /dev/null
    volumes:
      - ~:/opt/host
